-- MySQL Script generated by MySQL Workbench
-- Tue Mar 11 10:37:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CSC_4710_Project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CSC_4710_Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CSC_4710_Project` DEFAULT CHARACTER SET utf8 ;
USE `CSC_4710_Project` ;

-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Gender` CHAR(1) NOT NULL,
  `Age` INT NOT NULL COMMENT 'Char Set\nM-Male\nF-Female',
  `StylePerference` VARCHAR(15) NOT NULL,
  `Body_Type` VARCHAR(15) NULL,
  `Location` TEXT(200) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Clothing_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Clothing_Item` (
  `idClothing_Item` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `ImageURL` TEXT(128) NULL COMMENT 'Probably can change Datatype to BLOB to allow for direct insertion of image or can leave as TEXT to access thru set directory or file location',
  `Category` VARCHAR(45) NULL,
  `Color` VARCHAR(15) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL DEFAULT 'Generic' COMMENT 'Also can share same data as Fashion_Trend.Designer_name\n',
  `Type_Of` VARCHAR(30) NOT NULL COMMENT 'Specifies what part of the body it covers',
  `Description` MEDIUMTEXT NULL,
  `TargetGender` CHAR(1) NULL,
  PRIMARY KEY (`idClothing_Item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `Location` TEXT(200) NULL,
  `Date` DATETIME NOT NULL,
  `Description` TEXT(200) NULL,
  `Dresscode` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Fashion_Trend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Fashion_Trend` (
  `idFashion Trend` INT NOT NULL AUTO_INCREMENT,
  `Source_URL` TEXT(128) NOT NULL,
  `Season` VARCHAR(10) NULL,
  `Style_Primary` VARCHAR(45) NOT NULL,
  `Style_Secondary` VARCHAR(45) NULL,
  `Style_Tertiary` VARCHAR(45) NULL,
  `Designer_Name_Primary` VARCHAR(45) NOT NULL DEFAULT 'Generic',
  `Designer_Name_Secondary` VARCHAR(45) NULL,
  `Designer_Name_Tertiary` VARCHAR(45) NULL,
  `Color_Primary` VARCHAR(45) NOT NULL DEFAULT 'Generic',
  `Color_Secondary` VARCHAR(45) NULL,
  `Color_Tertiary` VARCHAR(45) NULL,
  PRIMARY KEY (`idFashion Trend`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Owns_Personal_Wardrobe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Owns_Personal_Wardrobe` (
  `idUser` INT NOT NULL COMMENT 'Note: Decided to have a many-to-many Identifying relationship to better illustrate a digital wardrobe',
  `idClothing_Item` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idClothing_Item`),
  INDEX `fk_User_has_Clothing_Item_Clothing_Item1_idx` (`idClothing_Item` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Clothing_Item_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `CSC_4710_Project`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Clothing_Item_Clothing_Item1`
    FOREIGN KEY (`idClothing_Item`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Scheduled`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Scheduled` (
  `idUser` INT NOT NULL,
  `idEvent` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idEvent`),
  INDEX `fk_User_has_Event_Event1_idx` (`idEvent` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Event_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `CSC_4710_Project`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Event_Event1`
    FOREIGN KEY (`idEvent`)
    REFERENCES `CSC_4710_Project`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Weather_Conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Weather_Conditions` (
  `idWeather_Conditions` INT NOT NULL AUTO_INCREMENT,
  `Humidty` DECIMAL(2,1) NOT NULL,
  `Date` DATE NOT NULL,
  `Temperature_High` TINYINT(3) NOT NULL COMMENT 'Highest Temp of that day',
  `Temperature_Low` TINYINT(3) NOT NULL COMMENT 'Lowest Temp of that Day',
  `Location` TEXT(200) NOT NULL,
  `Preciptation` TINYINT(2) NULL,
  PRIMARY KEY (`idWeather_Conditions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Outfit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Outfit` (
  `idOutfit` INT NOT NULL AUTO_INCREMENT,
  `id_User` INT NULL COMMENT 'Default is NULL for temporary unassignment at run time\n',
  `Top` INT NULL,
  `Bottom` INT NULL,
  `Shoes` INT NULL,
  `Hat` INT NULL,
  `Coat` INT NULL,
  `Description` TEXT(200) NULL,
  `Style` VARCHAR(45) NULL COMMENT 'Will be used to match best user',
  PRIMARY KEY (`idOutfit`),
  INDEX `fk_Outfit_User1_idx` (`id_User` ASC) VISIBLE,
  INDEX `fk__idx` (`Top` ASC) VISIBLE,
  INDEX `fk_Bottom_idx` (`Bottom` ASC) VISIBLE,
  INDEX `fk_Shoes_idx` (`Shoes` ASC) VISIBLE,
  INDEX `fk_Coat_idx` (`Coat` ASC) VISIBLE,
  INDEX `fk_Hat_idx` (`Hat` ASC) VISIBLE,
  CONSTRAINT `fk_Outfit_User1`
    FOREIGN KEY (`id_User`)
    REFERENCES `CSC_4710_Project`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Top`
    FOREIGN KEY (`Top`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bottom`
    FOREIGN KEY (`Bottom`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shoes`
    FOREIGN KEY (`Shoes`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coat`
    FOREIGN KEY (`Coat`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hat`
    FOREIGN KEY (`Hat`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`Favorited_Outfits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`Favorited_Outfits` (
  `idOutfit` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idOutfit`, `idUser`),
  INDEX `fk_Outfit_has_User_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Outfit_has_User_Outfit1`
    FOREIGN KEY (`idOutfit`)
    REFERENCES `CSC_4710_Project`.`Outfit` (`idOutfit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Outfit_has_User_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `CSC_4710_Project`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`IsTop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`IsTop` (
  `idClothing_Item` INT NOT NULL,
  `SleeveType` CHAR(15) NULL DEFAULT 'Regular',
  PRIMARY KEY (`idClothing_Item`),
  CONSTRAINT `fk_IsShirt_Clothing_Item1`
    FOREIGN KEY (`idClothing_Item`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`IsBottom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`IsBottom` (
  `idClothing_Item` INT NOT NULL,
  `LengthCoverage` VARCHAR(15) NULL,
  `Fit` VARCHAR(15) NULL COMMENT 'Refers to tightness to body; ie. Slim jeans, tights, baggy',
  PRIMARY KEY (`idClothing_Item`),
  INDEX `fk_IsBottom_Clothing_Item1_idx` (`idClothing_Item` ASC) VISIBLE,
  CONSTRAINT `fk_IsBottom_Clothing_Item1`
    FOREIGN KEY (`idClothing_Item`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`IsFootWear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`IsFootWear` (
  `idClothing_Item` INT NOT NULL,
  `WalkingType` VARCHAR(15) NULL DEFAULT 'Walking',
  PRIMARY KEY (`idClothing_Item`),
  CONSTRAINT `fk_IsFootWear_Clothing_Item1`
    FOREIGN KEY (`idClothing_Item`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`IsCoat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`IsCoat` (
  `idClothing_Item` INT NOT NULL,
  `IsWaterResistant` TINYINT NULL DEFAULT 0,
  `Heaviness` CHAR(10) NULL COMMENT 'Referring to how much warm/protection from elements',
  PRIMARY KEY (`idClothing_Item`),
  CONSTRAINT `fk_IsCoat_Clothing_Item1`
    FOREIGN KEY (`idClothing_Item`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`IsDress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`IsDress` (
  `idClothing_Item` INT NOT NULL,
  `Formality` VARCHAR(15) NULL,
  PRIMARY KEY (`idClothing_Item`),
  CONSTRAINT `fk_IsDress_Clothing_Item1`
    FOREIGN KEY (`idClothing_Item`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`IsHeadwear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`IsHeadwear` (
  `idClothing_Item` INT NOT NULL,
  `Heaviness` CHAR(10) NULL,
  PRIMARY KEY (`idClothing_Item`),
  CONSTRAINT `fk_IsHeadwear_Clothing_Item1`
    FOREIGN KEY (`idClothing_Item`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CSC_4710_Project`.`With_Accessory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CSC_4710_Project`.`With_Accessory` (
  `Parent_Outfit_ID` INT NOT NULL,
  `Accessory` INT NOT NULL COMMENT 'Must be categorized as ‘Isother’ from the Clothing_Item\n',
  PRIMARY KEY (`Parent_Outfit_ID`),
  INDEX `fk_With_Accessory_Clothing_Item1_idx` (`Accessory` ASC) VISIBLE,
  CONSTRAINT `fk_With_Accessory_Outfit1`
    FOREIGN KEY (`Parent_Outfit_ID`)
    REFERENCES `CSC_4710_Project`.`Outfit` (`idOutfit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_With_Accessory_Clothing_Item1`
    FOREIGN KEY (`Accessory`)
    REFERENCES `CSC_4710_Project`.`Clothing_Item` (`idClothing_Item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `CSC_4710_Project`;

DELIMITER $$
USE `CSC_4710_Project`$$
CREATE DEFINER = CURRENT_USER TRIGGER `CSC_4710_Project`.`IsDress_AFTER_INSERT` AFTER INSERT ON `IsDress` FOR EACH ROW
BEGIN
	-- Automatically makes any dress upon insertion, Clothing_item.TargetGender = F; for females
    UPDATE Clothing_Item
    SET TargetGender = 'F'
    WHERE Clothing_Item.idClothing_Item = NEW.idClothing_Item;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
